import { readFileSync } from 'node:fs'; import { resolve } from 'node:path'; import { createRequire } from 'node:module';
import type { Adjudication, CalibrationReport, DeterministicEvaluation, EvidencePacket, JevEvaluation } from './types.js';
export class ValidationError extends Error { constructor(public artifact:string, public details:string[]){ super(`${artifact} validation failed: ${details.join('; ')}`); } }
const schemaPath=(name:string)=>resolve(process.cwd(),'../../rigor/schemas',`${name}.schema.json`);
const require=createRequire(import.meta.url); let validators:Record<string,any>|null=null;
function ajvValidator(name:string):any|null { if(validators?.[name]) return validators[name]; if(validators===null){ validators={}; try{ const Ajv2020=require('ajv/dist/2020').default; const ajv=new Ajv2020({allErrors:true,strict:true}); for(const n of ['evidence-packet','jev-evaluation','deterministic-evaluation','adjudication','calibration-report']) validators[n]=ajv.compile(JSON.parse(readFileSync(schemaPath(n),'utf8'))); }catch{ validators={}; } } return validators[name]??null; }
function assertNoExtra(v:any, allowed:string[], e:string[]){ for(const k of Object.keys(v)) if(!allowed.includes(k)) e.push(`additional property ${k}`); }
function manualEvidence(v:any):string[]{ const e:string[]=[]; if(!v||typeof v!=='object') return ['must be object']; const keys=['schema_version','packet_id','packet_version','branch_id','hypothesis_id','claim','claim_type','non_claims','evidence_boundary_date','sources','data','design','statistics','rivals','controls','known_disagreements','attachments']; for(const k of keys)if(!(k in v))e.push(`missing ${k}`); assertNoExtra(v,keys,e); if(v.schema_version!=='1.0')e.push('schema_version'); if(typeof v.packet_id!=='string'||!v.packet_id)e.push('packet_id'); if(!['descriptive','associational','predictive','causal','mechanistic'].includes(v.claim_type))e.push('claim_type'); const d=v.data; const dk=['dataset','version','checksum','discovery_status','confirmation_status','prior_exposure','preregistration_timestamp','target_exposure_timestamp']; if(!d||typeof d!=='object')e.push('data'); else { for(const k of dk)if(!(k in d))e.push(`data missing ${k}`); assertNoExtra(d,dk,e); if(!['inspected','uninspected','mixed','unknown'].includes(d.discovery_status))e.push('discovery_status'); if(!['untouched','previously_inspected','prospective','results_blind','none','unknown'].includes(d.confirmation_status))e.push('confirmation_status'); } return e; }
function validate<T>(name:string,value:unknown,manual:(v:any)=>string[]):T { const fn=ajvValidator(name); if(fn){ if(!fn(value)) throw new ValidationError(name,(fn.errors??[]).map((x:any)=>`${x.instancePath||'/'} ${x.message}`)); return value as T; } const e=manual(value); if(e.length)throw new ValidationError(name,e); return value as T; }
export const validateEvidencePacket=(v:unknown)=>validate<EvidencePacket>('evidence-packet',v,manualEvidence);
export const validateJevEvaluation=(v:unknown)=>validate<JevEvaluation>('jev-evaluation',v,(x:any)=>x?.model_id==='typesafe/jev-1.13'?[]:['model_id']);
export const validateDeterministicEvaluation=(v:unknown)=>validate<DeterministicEvaluation>('deterministic-evaluation',v,(x:any)=>x?.rules&&typeof x.promotion_blocked==='boolean'?[]:['rules/promotion_blocked']);
export const validateAdjudication=(v:unknown)=>validate<Adjudication>('adjudication',v,(x:any)=>['PASS','PARTIAL','FAIL','BLOCKED','N/A'].includes(x?.gate_status)?[]:['gate_status']);
export const validateCalibrationReport=(v:unknown)=>validate<CalibrationReport>('calibration-report',v,(x:any)=>['ADVISORY_ONLY','CALIBRATED_APPROVED'].includes(x?.authority_status)?[]:['authority_status']);
