export type GateStatus = 'PASS' | 'PARTIAL' | 'FAIL' | 'BLOCKED' | 'N/A';
export type CriterionStatus = 'PASS' | 'FAIL' | 'UNCERTAIN' | 'N/A';
export type AuthorityStatus = 'ADVISORY_ONLY' | 'CALIBRATED_APPROVED';
export interface EvidencePacket { schema_version:'1.0'; packet_id:string; packet_version:number; branch_id:string; hypothesis_id:string; claim:string; claim_type:'descriptive'|'associational'|'predictive'|'causal'|'mechanistic'; non_claims:string[]; evidence_boundary_date:string; sources:Array<{source_id:string;type:'peer_reviewed'|'preprint'|'data'|'code'|'review'|'primary_source'|'secondary_source';citation:string;claim_relevance:string;limitations:string[]}>; data:{dataset:string;version:string|null;checksum:string|null;discovery_status:'inspected'|'uninspected'|'mixed'|'unknown';confirmation_status:'untouched'|'previously_inspected'|'prospective'|'results_blind'|'none'|'unknown';prior_exposure:string;preregistration_timestamp:string|null;target_exposure_timestamp:string|null}; design:Record<string,unknown>; statistics:Record<string,unknown>; rivals:Array<Record<string,unknown>>; controls:Array<Record<string,unknown>>; known_disagreements:string[]; attachments:Array<{path:string;sha256:string}>; }
export interface RubricQuestion { id:string; type:'noul'|'choice'|'score'; instructions:string; criteria:Record<string,string>; consequential:boolean; }
export interface Rubric { rubric_version:string; rubric_id:string; title:string; questions:RubricQuestion[]; }
export interface RuleResult { rule_id:string; status:CriterionStatus; authoritative:true; rationale:string; affected_gate_ids:string[]; }
export interface DeterministicEvaluation { schema_version:'1.0'; packet_id:string; rules:Record<string,RuleResult>; promotion_blocked:boolean; }
export interface JevCriterionResult { criterion_id:string; status:CriterionStatus; probability:number|null; answer:unknown; }
export interface JevEvaluation { schema_version:'1.0'; packet_id:string; model_id:'typesafe/jev-1.13'; rubric_version:string; packet_sha256:string; status:'OK'|'MODEL_ERROR'; promotion_eligible:false; criteria:JevCriterionResult[]; provider_metadata:Record<string,unknown>; error?:string; }
export interface CalibrationReport { schema_version:'1.0'; authority_status:AuthorityStatus; threshold_policy:null|{pass:number;escalate_below:number}; gold_case_count:number; human_reviewed_case_count:number; accuracy:number; balanced_accuracy:number; false_pass_rate:number; false_fail_rate:number; brier_score:number; disagreement_rate:number; per_rubric:Record<string,{count:number;accuracy:number}>; }
export interface Disagreement { criterion_id:string; channels:Record<string,unknown>; consequential:boolean; escalation_reason:string; resolution_status:'UNRESOLVED'|'RESOLVED'; }
export interface Adjudication { schema_version:'1.0'; packet_id:string; gate_status:GateStatus; promotion_eligible:boolean; requires_human_review:boolean; disagreements:Disagreement[]; rationale:string[]; prior_project_status?:string; }
